name: SpringBoot CI/CD with Ansible

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build Spring Boot App
        run: |
          cd springboot-app
          mvn clean package -DskipTests

      - name: Upload Artifact (JAR)
        uses: actions/upload-artifact@v3
        with:
          name: springboot-jar
          path: springboot-app/target/demo-0.0.1-SNAPSHOT.jar

      - name: Copy JAR to Ansible Server (Using SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 98.93.188.216
          username: ec2-user
          key: ${{ secrets.ANSIBLE_SSH_KEY }}
          source: "springboot-app/target/demo-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/Ansible-Automation-On-AWS/springboot-ansible-deploy/springboot-app/target/"

      - name: Run Ansible Playbook via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.93.188.216
          username: ec2-user
          key: ${{ secrets.ANSIBLE_SSH_KEY }}
          script: |
            cd /home/ec2-user/Ansible-Automation-On-AWS/springboot-ansible-deploy/ansible
            ansible-playbook -i hosts.ini deploy.yml
